#!/bin/bash

exec 3< <(egrep -o "class\sTOOJ_EXPORT\s(\S+)"  ../src -R 2>&1)
#../src/rpchub.h:class RpcHub

pattern="\.\.\/src\/([a-z]+)\.h\:class\sTOOJ_EXPORT\s(\w+)"

while read line; do
	if [[ $line =~ $pattern ]]; then
		#dir=${BASH_REMATCH[1]}
		header=${BASH_REMATCH[1]}
		class=${BASH_REMATCH[2]}
		
		#mkdir -p $dir
		echo "#include \"../src/$header.h\"" > $class
		echo "#include \"../src/$header.h\"" > "$header.h"
		#echo "#include \"../../src/$dir/src/$header.h\"" > $dir/$class
	fi
done <&3
exec 3<&-
#echo "$f"
